apiVersion: v1
kind: Template
labels:
  app: ${NAME}
  template: ${NAME}
message: |-
  A simple Machine Learning example (sentiment detection) service has been scheduled for creation in your project, and should be soon available at: https://${NAME}.${APPLICATION_DOMAIN_SUFFIX}
  Pulling images might take some minutes to complete, so please be patient. You can follow progress on your projects overview page.
metadata:
  annotations:
    description: This template deploys A simple Machine Learning (sentiment detection) service.
    iconClass: fa fa-robot
    openshift.io/display-name: ML Example
    openshift.io/documentation-url: https://github.com/tdeneke/rahti-ml-examples 
    openshift.io/support-url: https://www.csc.fi/contact-info
    openshift.io/long-description: 
    openshift.io/provider-display-name: CSC
    tags: rahti-ml-examples
    template.openshift.io/bindable: "false"
  name: rahti-ml-examples

objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how the service is deployed.
    labels:
      app: ${NAME} 
    name: ${NAME}-dc
  spec:
    replicas: 1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${NAME} 
      spec:
        containers:
        - name: ${NAME} 
          image: ${SOURCE_IMAGE}:${SOURCE_IMAGE_TAG} 
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: 2 
    
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      description: Exposes the services to public.    
    labels:
      app: ${NAME} 
    name: ${NAME}-route 
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${NAME}-srv
      weight: 100
    wildcardPolicy: None

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Defines an internal proxy. 
    labels:
      app: ${NAME} 
    name: ${NAME}-srv 
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${NAME}-dc


####################

parameters:
- description: Unique identifier for your application. 
  displayName: Application Name
  name: NAME
  value: rahti-ml-examples
  required: true

- description: The IMAGE with the application code (change the default only if you know what you are doing). 
  displayName: Source Image
  name: SOURCE_IMAGE
  value: tdeneke/tf2-imdb-cuda
  required: true

- description: The tag of the IMAGE (latest). 
  displayName: Source Repository Branch
  name: SOURCE_IMAGE_TAG
  value: latest 
  required: true

- description: The exposed hostname suffix that will be used to create routes for app
  displayName: Application Hostname Suffix
  name: APPLICATION_DOMAIN_SUFFIX
  required: true
  value: rahtiapp.fi
